print("\t/t/t Personal Information")
last_name = input("Please enter your last name \n")
first_name = input("Please enter your first name \n")
age = input("Please enter your age \n")
sex = input("Please enter your sex \n")
contact_number = input("Please enter your contact number \n")
address = input("Please enter your address \n")
b_day = input("Please enter your b_day \n")
birthplace = input("Please enter your birthplace \n")
email = input("Please enter your email \n") 
religion = input("Please enter your religion \n")
civil_status = input("Please enter your civil status \n")
citizenship = input("Please enter your citizenship \n")
height = input("Please enter your height \n")
weight = input("Please enter your weight \n")
father_name = input("Please enter your father name \n")
mother_name = input("Please enter your mother name \n")
print("\t/t/t Personal Information")
print("Hi guys," + " " + "my name is" + " " + first_name + " " + last_name + "." + " " + "I am" + " " + age + " " + "years old" + "." + " " + "I lived at" + " " + address + "." + " ")
print("I am" + " " + sex + "." + " " + "My contact number is" + " " + contact_number + "." + " " + "My email is" + " " + email + "." + " ")
print("I was born in" + " " + b_day + " " + "at" + " " + birthplace + "." + " " + "I am" + " " + religion + "." + " " + "I am" + " " + civil_status + "." + " ")
print("I am" + " " + citizenship + "." + " " + "My height is" + " " + height + " " + "and" + " " + "I" + " " + "weigh" + " " + weight + "." + " ")
print("My father`s name is" + " " + father_name + " " + "and" + " " + "my mother`s name is" + " " + mother_name + ".")